#!/usr/bin/bash


# ------------------------------
# User Aliases

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rm='rm -i'
alias vim='vim -O'
alias ceph-shell='sudo cephadm shell --fsid bdb909d2-bc39-11ec-981f-abd9703f3e17 -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring'


# ------------------------------
# Signal that this file has been invoked
echo "===> Loaded bash aliases"
