#!/usr/bin/bash


# ------------------------------
# User bash environment configuration

# ..............................
# Non-idempotent configuration (execute once per environment)

if [[ $BASH_ENV_LOADED -eq 0 ]]; then
    export BASH_ENV_LOADED=$(( 1 ))

    # bank the vanilla path for convenience
    export default_path="${PATH}:/usr/local/bin:${HOME}/.local/bin:${HOME}/bin"

    # If we don't have terminfo built, use xterm
    if [[ $(find "${HOME}/.terminfo" -name '*alacritty*' | wc -l) -eq 2 ]]; then
        export TERMINAL=alacritty

    else
        export TERMINAL=xterm-256color

    fi

    # if pyenv is available, initialize it for this environment
    type pyenv > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        eval "$(pyenv init -)"
        eval "$(pyenv init --path)"
    fi
fi

# ..............................
# Idempotent configuration (may be executed many times)

# >> common env variables
export EDITOR=vim
export GIT_EDITOR=vim
export PAGER=less

# >> path-related env variables

# this serves as a "registry" of installed tools
toolbox_path="${HOME}/toolbox"

# reconstruct PATH using the vanilla PATH
export PATH="${toolbox_path}/bin":${default_path}


# ------------------------------
# Signal that this file was invoked
echo "===> Loaded bash environment"
