#!/bin/bash


# ------------------------------
# Global and command-line args

config_root="${1:?"Please provide the top-level config directory"}"

# source paths of configuration files
path_to_configs_vim="${config_root}/common/vim/vimrc"
path_to_configs_bash="${config_root}/mac/bash"
path_to_configs_fish="${config_root}/mac/fish"
path_to_configs_alacritty="${config_root}/mac/alacritty"
path_to_configs_tmux="${config_root}/mac/tmux"

# destination paths of configuration files
path_to_home_config="${HOME}/.config"
path_to_home_fish="${path_to_home_config}/fish"
path_to_home_alacritty="${path_to_home_config}/alacritty"

path_to_home_vim="${HOME}/.vimrc"


# ------------------------------
# Validation

# >> At some point, add validation that we're on a mac


# ------------------------------
# Main logic

# ..............................
# All of the configurations that go directly into $HOME

# [vim] symlink the file
echo "[vim] Linking configuration files..."
ln -s "${path_to_configs_vim}" "${path_to_home_vim}"

# [bash] symlink each file
for bash_config_file in $(ls "${path_to_configs_bash}"); do
    [[ -f "${HOME}/.${bash_config_file}" ]] && continue

    config_filepath="${path_to_configs_bash}/${bash_config_file}"
    symlink_filepath="${HOME}/.${bash_config_file}"

    echo -e "\t>> '${symlink_filepath}'"
    ln -s "${config_filepath}" "${symlink_filepath}"
done


# ..............................
# All of the configurations that go into $HOME/.config
mkdir -p ${path_to_home_config}

# [fish] symlink the directory
if [[ -d "${path_to_home_config}" && ! -d "${path_to_home_fish}" ]]; then
   ln -s "${path_to_configs_fish}" "${path_to_home_fish}"
fi

# [alacritty] symlink the directory
if [[ ! -d "${path_to_home_alacritty}" ]]; then
    ln -s "${path_to_configs_alacritty}" "${path_to_home_alacritty}"
fi

# tmux theme setup
if [[ ! -d "${path_to_configs_tmux}/themes" ]]; then
    mkdir -p "${path_to_configs_tmux}/themes"
    path_to_nordtheme="${config_root}/external/nord-tmux"

    if [[ -e "${path_to_nordtheme}/nord.tmux" ]]; then
        ln -s "${path_to_nordtheme}" "${path_to_configs_tmux}/themes/nord-tmux"

    else
        echo "tmux theme not found. make sure the submodule is setup."

    fi
fi
