#!/usr/bin/bash


# ------------------------------
# User aliases

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rm='rm -i'


# ------------------------------
# Signal that this file has been invoked
echo "===> Loaded bash aliases"
