#!/usr/bin/bash


# ------------------------------
# User bash environment configuration


# ..............................
# Non-idempotent configuration (execute once per environment)

if [[ $BASH_ENV_LOADED -eq 0 ]]; then
    export BASH_ENV_LOADED=$(( 1 ))

    # bank the vanilla path for convenience
    export default_path="${PATH}"

    # If we don't have terminfo built, use xterm
    if [[ $(find "${HOME}/.terminfo" -name '*alacritty*' | wc -l) -eq 2 ]]; then
        export TERMINAL=alacritty

    else
        export TERMINAL=xterm-256color

    fi

    # if pyenv is available, initialize it for this environment
    type pyenv > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        eval "$(pyenv init -)"
    fi

    # if nvm is available, initialize it for this environment
    initnvm_path="/usr/share/nvm/init-nvm.sh"
    [[ -f "${initnvm_path}" ]] && source "${initnvm_path}"
fi


# ..............................
# Idempotent configuration (may be executed many times)

# >> common env variables
export EDITOR=vim
export GIT_EDITOR=vim
export PAGER=less

# >> path-related env variables

# this is where all installed tools should be based
toolbox_path="${HOME}/toolbox"

# reconstruct PATH using the vanilla PATH
export PATH="${toolbox_path}/bin":${default_path}

# for pyenv and poetry to orient themselves
export PYENV_ROOT="${toolbox_path}/pyenv"
export POETRY_HOME="${toolbox_path}/poetry"

[[ -f "${HOME}/.cargo/env" ]] && source "${HOME}/.cargo/env"


# ------------------------------
# Signal that this file was invoked
echo "===> Loaded bash environment"
