#!/bin/sh

/usr/bin/autocutsel -fork &
/usr/bin/autocutsel -selection PRIMARY -fork &
/usr/bin/xscreensaver -no-splash &
/usr/lib/notification-daemon/notification-daemon &

/usr/bin/urxvtd -q -f -o &
/usr/bin/ibus-daemon -xd

exec awesome
