# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh-hist
HISTSIZE=10000
SAVEHIST=10000

#set options
setopt appendhistory notify
setopt interactivecomments

unsetopt beep

#use vim keybindings
bindkey -v

#initialize completion (comp)
zstyle :compinstall filename '/home/drin/.zshrc'
autoload -Uz compinit
compinit

#initialize prompt
autoload -U promptinit
promptinit
pt_username="%{$fg[red]%}%n"
pt_hostname="%{$fg[red]%}%m"
pt_time="%{$fg[yellow]%}%T"
pt_cwd="%{$fg[green]%}%/"

PROMPT="[${pt_time} ${pt_username}%{$reset_color%}@${pt_hostname}] ${pt_cwd}%{$reset_color%} "
