alias vim 'vim -O'
alias prev 'cd $dirprev[-1]'
alias bio-sql 'psql -hlocalhost -Udrin bio'
alias external-ip 'dig @resolver1.opendns.com ANY myip.opendns.com +short'
alias vpn-ucsc 'sudo openconnect --verbose 128.114.102.44:443'
